[package]
name = "event_bus_backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10"
ic-cdk = "0.10.0"  # Use the appropriate version
ic-cdk-macros = "0.6.0"  # Use the appropriate version
serde = { version = "1.0", features = ["derive"] }
