[package]
name = "loans_backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.12"
ic-cdk-macros = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
candid = "0.10"
