[package]
name = "trust_ai_backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10.17"
ic-cdk = "0.13.6"
ic-cdk-macros = "0.13.2"
serde = { version = "1.0", features = ["derive"] }
ic_principal = "0.1.1"